- name: Download the HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp.asc
    mode: '0644'

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    filename: 'hashicorp'

- name: Update APT cache and install Terraform
  apt:
    name: terraform
    state: present
    update_cache: yes

