- name: Ensure the /etc/systemd/system/ssh.socket.d directory exists
  file:
    path: /etc/systemd/system/ssh.socket.d/
    state: directory
    mode: '0755'

- name: Create /etc/systemd/system/ssh.socket.d/port222.conf to make SSH listen on port 222 too
  copy:
    content: |
      [Socket]
      ListenStream=222
    dest: /etc/systemd/system/ssh.socket.d/port222.conf
    mode: '0644'
      
